### ISSUE TITLE
create Question model

### ISSUE THREAD

**Issue by otekolste** [otekolste/answer-hive#11]

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by otekolste** [comment]
![Image](https://github.com/user-attachments/assets/602fd550-94c6-4669-9646-f8a34f006c1d)

**Comment by otekolste** [comment]
Note: Post to tag relation is many to many and will be accessed through another model, called PostTag
