### ISSUE TITLE
Set up loggin form 

### ISSUE THREAD

**Issue by jjackson0228** [otekolste/answer-hive#6]
Loggin form with username/email and password. And keep the sensitive data hidden with environment variables

**Comment by Ashleighjg** [comment]
https://github.com/otekolste/answer-hive/pull/22

**Comment by Ashleighjg** [comment]
![Image](https://github.com/user-attachments/assets/13a42987-23b2-4cfb-b5c0-13606856e243)



![Image](https://github.com/user-attachments/assets/a052282a-8ef2-4a62-b36e-a86779c9fdb7)
